server
{
#    key       value
	listen		8085;
#       key      value
	server_name	localhost;

#    key      value
	root	./site/limits;

#     key  [     array     ]
	methods	GET POST DELETE;

#      key     [ array of key  ]     value
	error_page	400 401 401 403	./errors/4XX.html;

#             key          value unit
	client_max_body_size	32k;

#   sub-node   key
	location	/
	{
#        key           value
		index		index.html;
#        key       value
		methods		GET;
#        key       [array]
		methods		[GET];
#        key       value
		autoindex	off;
	}

#   sub-node      key
	location	/upload
	{
#          key     [ array  ]
		methods		GET POST;
#          key     value
		autoindex	off;
	}

#   sub-node        key
	location	/readonly
	{
#         key      value
		methods		GET;
#         key      value
		autoindex	off;
	}
}
